//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtlasTaskmaster {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.0.1.0")]
    internal sealed partial class Taskmaster : global::System.Configuration.ApplicationSettingsBase {
        
        private static Taskmaster defaultInstance = ((Taskmaster)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Taskmaster())));
        
        public static Taskmaster Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>path1</string>\r\n  <string>path2</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ServicePaths {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ServicePaths"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>serviceWindowName1</string>\r\n  <string>serviceWindowName2</string>\r\n</Arra" +
            "yOfString>")]
        public global::System.Collections.Specialized.StringCollection ServiceWindowNames {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ServiceWindowNames"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>true</string>\r\n  <string>true</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ServiceKeepRunning {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ServiceKeepRunning"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int ServiceUpdateRateSeconds {
            get {
                return ((int)(this["ServiceUpdateRateSeconds"]));
            }
        }
    }
}
